const NotificationType = Object.freeze({
  LEAVE_APPROVED: 'LEAVE_APPROVED',
  ORGANIZATION_MAKE_PAYMENT: 'ORGANIZATION_MAKE_PAYMENT',
  ORGANIZATION_DEACTIVATED: 'ORGANIZATION_DEACTIVATED',
  ORGANIZATION_ARCHIVE:'ORGANIZATION_ARCHIVE',
  ANNOUNCEMENT:'ANNOUNCEMENT',
  PROJECT_UPDATE:"PROJECT_UPDATE",
  MEETING_UPDATE:"MEETING_UPDATE",
  MEETING_CREATED:"MEETING_CREATED",
  TICKETS_UPDATE:"TICKETS_UPDATE",
  PROJECT_CREATED:"PROJECT_CREATED",
  MODULE_CREATED:"MODULE_CREATED",
  SPRINT_CREATED:"SPRINT_CREATED",
  TICKET_CREATED:"TICKET_CREATED"
});

module.exports = NotificationType;
