// Error types
export const SET_ERRORS = "SET_ERRORS";
export const SET_EMPTY_ERRORS = "SET_EMPTY_ERRORS";
export const SET_ERROR_CODE = "SET_ERROR_CODE";

//Auth types
export const SET_LOGIN = "SET_LOGIN";
export const SET_LOGIN_FLOW_NEXT = "SET_LOGIN_FLOW_NEXT";
export const LOGOUT_USER = "LOGOUT_USER";
export const SET_SIGNUP_USER_INFO = "SET_SIGNUP_USER_INFO";
export const GET_PLANS = "GET_PLANS";
export const SET_COMPANY_DAYS_OFF = "SET_COMPANY_DAYS_OFF";
export const SET_COMPANY_WORKING_HOURS = "SET_COMPANY_WORKING_HOURS";
export const SET_MEMBER_DAYS_OFF = "SET_MEMBER_DAYS_OFF";
export const SET_USER_ROLE = "SET_USER_ROLE";
export const SET_LOADER = "SET_LOADER";
export const CLEAR_LOADER = "CLEAR_LOADER";
export const SET_ORGANIZATION_DATA = "SET_ORGANIZATION_DATA";
export const SET_AUTH_API_STATUS = "SET_AUTH_API_STATUS";
export const GET_INVITE_LINK_USERS = "GET_INVITE_LINK_USERS";

//Payment types
export const SET_BILLING_HISTORY = "SET_BILLING_HISTORY";

//Resources Types
export const SET_ALL_RESOURCES = "SET_ALL_RESOURCES";
export const SET_MEMBER_COUNT = "SET_MEMBER_COUNT";
export const SET_RESOURCE_OVERVIEW = "SET_RESOURCE_OVERVIEW";
export const SET_SINGLE_RSOURCE_DATA = "SET_SINGLE_RSOURCE_DATA";

//Project types
export const SET_ALL_PROJECTS = "SET_ALL_PROJECTS";
export const SET_SELECTED_MEMBERS = "SET_SELECTED_MEMBERS";
export const SET_ALL_PROJECT_COUNT = "SET_ALL_PROJECT_COUNT";
export const SET_PROJECT_OVERVIEW = "SET_PROJECT_OVERVIEW";
export const SET_SINGLE_PROJECT_DATA = "SET_SINGLE_PROJECT_DATA";
export const SET_BURNDOWN_CHART_DATA = "SET_BURNDOWN_CHART_DATA";
export const SET_TASK_PROGRESS_CHART = "SET_TASK_PROGRESS_CHART";
export const SET_ALL_PIN_PROJECTS = "SET_ALL_PIN_PROJECTS";
export const SET_PROJECT_ACTIVITY = "SET_PROJECT_ACTIVITY";
export const SET_PROJECT_EXPENSE_OVERVIEW = "SET_PROJECT_EXPENSE_OVERVIEW";
export const SET_PROJECT_CARD_COUNT_DATA = "SET_PROJECT_CARD_COUNT_DATA";

// Project Files
export const SET_ALL_FILES = "SET_ALL_FILES";

//Project Overview Types
export const SET_SCHEDULE_INDICATOR = "SET_SCHEDULE_INDICATOR";
export const SET_SCHEDULE_INDICATOR_TASK_COMPLETION =
  "SET_SCHEDULE_INDICATOR_TASK_COMPLETION";
export const SET_AVG_COST_OF_EMP = "SET_AVG_COST_OF_EMP";
export const SET_TOTAL_COST_OF_EMP = "SET_TOTAL_COST_OF_EMP";
export const SET_HEALTH_STATUS_OF_SPRINTS = "SET_HEALTH_STATUS_OF_SPRINTS";
export const SET_HEALTH_STATUS_OF_MODULES = "SET_HEALTH_STATUS_OF_MODULES";
export const SET_TASK_STATUS_GROUPING = "SET_TASK_STATUS_GROUPING";
export const SET_UPCOMING_SCRUM = "SET_UPCOMING_SCRUM";

//Project Progress types
export const SET_ESTIMATED_COST_VS_ACTUAL_COST_CHART_DATA =
  "SET_ESTIMATED_COST_VS_ACTUAL_COST_CHART_DATA";
export const SET_PLANNED_HOURS_VS_ACTUAL_HOURS_CHART_DATA =
  "SET_PLANNED_HOURS_VS_ACTUAL_HOURS_CHART_DATA";

//Project Scrums
export const SET_PROJECT_SCRUMS = "SET_PROJECT_SCRUMS";
export const SET_ALL_NOTES_OF_SINGLE_SCRUM = "SET_ALL_NOTES_OF_SINGLE_SCRUM";
export const SET_SIGNLE_SCRUM_DATA = "SET_SIGNLE_SCRUM_DATA";
export const SET_SINGLE_DOC_DATA = "SET_SINGLE_DOC_DATA";

//Report Types
export const SET_PROJECT_TASK_COMPLETION_STATUS =
  "SET_PROJECT_TASK_COMPLETION_STATUS";
export const SET_RESOURCE_DISTRIBUTION_COUNT =
  "SET_RESOURCE_DISTRIBUTION_COUNT";
export const SET_RESOURCE_DISTRIBUTION_PERCENT =
  "SET_RESOURCE_DISTRIBUTION_PERCENT";
export const SET_TOTAL_EXPENSE_THIS_MONTH = "SET_TOTAL_EXPENSE_THIS_MONTH";
export const SET_TOTAL_BILLED_AND_UNBILLED_EXPENSES_THIS_MONTH =
  "SET_TOTAL_BILLED_AND_UNBILLED_EXPENSES_THIS_MONTH";
export const SET_TOTAL_PAID_AND_TOTAL_INVOICED_AMOUNT =
  "SET_TOTAL_PAID_AND_TOTAL_INVOICED_AMOUNT";
export const SET_TOTAL_NUMBER_OF_INVOICES = "SET_TOTAL_NUMBER_OF_INVOICES";
export const SET_CLIENTS_COMPOSITION = "SET_CLIENTS_COMPOSITION";
export const SET_TOTAL_CLIENTS_COUNT = "SET_TOTAL_CLIENTS_COUNT";
export const SET_TOTAL_REVENUE_THIS_MONTH = "SET_TOTAL_REVENUE_THIS_MONTH";
export const SET_TOTAL_SUBSCRIPTION_COST_THIS_MONTH =
  "SET_TOTAL_SUBSCRIPTION_COST_THIS_MONTH";
export const SET_EXPENSE_VS_INCOME_CHART_DATA =
  "SET_EXPENSE_VS_INCOME_CHART_DATA";
export const SET_PAID_INVOICE_REPORT_ISSUED_CHART_DATA =
  "SET_PAID_INVOICE_REPORT_ISSUED_CHART_DATA";
export const SET_PROJECT_COUNTDOWN_IN_REPORTS =
  "SET_PROJECT_COUNTDOWN_IN_REPORTS";
export const SET_PROJECT_HEALTH = "SET_PROJECT_HEALTH";
export const SET_OVERALL_BUDGET_SPENT_CHART = "SET_OVERALL_BUDGET_SPENT_CHART";
export const SET_UTILIZED_HOURS_CHART_DATA = "SET_UTILIZED_HOURS_CHART_DATA";
export const SET_REVENUE_GENERATED_CHART_DATA =
  "SET_REVENUE_GENERATED_CHART_DATA";
export const SET_PROJECT_SUMMARY_CHART_DATA = "SET_PROJECT_SUMMARY_CHART_DATA";
export const SET_RESOURCE_SUMMARY_REPORT = "SET_RESOURCE_SUMMARY_REPORT";
export const SET_AVG_UTILIZATION_RATE_OF_RESOURCE =
  "SET_AVG_UTILIZATION_RATE_OF_RESOURCE";
export const SET_TASK_BY_PRIORITY_REPORT = "SET_TASK_BY_PRIORITY_REPORT";
export const SET_TASK_IMP_DISTRIBUTION_BY_PROJECT =
  "SET_TASK_IMP_DISTRIBUTION_BY_PROJECT";
export const SET_TASK_WITH_MOST_LOGGED_HOURS_OVERALL =
  "SET_TASK_WITH_MOST_LOGGED_HOURS_OVERALL";
export const SET_DUE_INVOICE_AMOUNT = "SET_DUE_INVOICE_AMOUNT";
export const SET_DISTRIBUTION_CHART_DATA = "SET_DISTRIBUTION_CHART_DATA";
export const SET_TICKET_SUMMARY_TILL_DATE_AND_MONTH =
  "SET_TICKET_SUMMARY_TILL_DATE_AND_MONTH";
export const SET_TICKET_TABLE_DATA = "SET_TICKET_TABLE_DATA";
export const SET_EXPENSE_VS_INCOME_TABLE_DATA =
  "SET_EXPENSE_VS_INCOME_TABLE_DATA";
export const SET_INVOICE_TABLE_DATA = "SET_INVOICE_TABLE_DATA";
export const SET_LEAVES_REPORT_DATA_TABLE = "SET_LEAVES_REPORT_DATA_TABLE";
export const SET_CLIENT_DETAIL_REPORT_TABLE_DATA =
  "SET_CLIENT_DETAIL_REPORT_TABLE_DATA";
export const SET_TASK_STATUS_REPORT_TABLE_DATA =
  "SET_TASK_STATUS_REPORT_TABLE_DATA";
export const SET_NUMBER_OF_TICKETS_RAISED_BY_REASONS_CHART =
  "SET_NUMBER_OF_TICKETS_RAISED_BY_REASONS_CHART";
export const SET_RESOURCE_TIMESHEET_TABLEDATA =
  "SET_RESOURCE_TIMESHEET_TABLEDATA";
export const SET_COMPOSITION_OF_LEAVE = "SET_COMPOSITION_OF_LEAVE";
export const SET_TOTAL_COMPANY_DAYOFFS = "SET_TOTAL_COMPANY_DAYOFFS";
export const SET_DISTRIBUTION_OF_TASK_BY_PROJECT =
  "SET_DISTRIBUTION_OF_TASK_BY_PROJECT";
export const SET_LAST_MONTH_LEAVES_BY_EMPLOYEE =
  "SET_LAST_MONTH_LEAVES_BY_EMPLOYEE";

//Socket types
export const SET_ALL_NOTIFICATIONS = "SET_ALL_NOTIFICATIONS";
export const SET_ALL_ANNOUNCEMENT = "SET_ALL_ANNOUNCEMENT";
export const SET_NEW_MEESAGE_STATUS = "SET_NEW_MEESAGE_STATUS";
export const SET_NEW_ANNOUNCEMENT_STATUS = "SET_NEW_ANNOUNCEMENT_STATUS";
export const SET_NEW_NOTIFICATION_STATUS = "SET_NEW_NOTIFICATION_STATUS";

//Kanban types

export const SET_KANBAN_BOARDS = "SET_KANBAN_BOARDS";
export const SET_KANBAN_VIEW = "SET_KANBAN_VIEW";
export const SET_STACKLIST_OF_BOARD = "SET_STACKLIST_OF_BOARD";

// Calender types
export const SET_SELECTED_DATE = "SET_SELECTED_DATE";
export const SET_SELECTED_DATE_DATA = "SET_SELECTED_DATE_DATA";
export const SET_ONLEAVE_TODAY = "SET_ONLEAVE_TODAY";
export const SET_AVAILABLE_LEAVES = "SET_AVAILABLE_LEAVES";

// Client types
export const SET_ALL_CLIENTS = "SET_ALL_CLIENTS";
export const SET_CLIENT_OVERVIEW = "SET_CLIENT_OVERVIEW";
export const SET_API_STATUS = "SET_API_STATUS";
export const SET_CLIENT_COUNT = "SET_CLIENT_COUNT";
export const SET_TOTAL_CLIENT_THIS_MONTH = "SET_TOTAL_CLIENT_THIS_MONTH";

// Finance Types
export const SET_ALL_ANVOICES = "SET_ALL_ANVOICES";
export const SET_FINANCE_SUBSCIPTION = "SET_FINANCE_SUBSCIPTION";
export const SET_ALL_SUBSCRIPTION_COUNT = "SET_ALLSUBSCRIPTION_COUNT";
export const SET_SUBSCRIPTION_OVERVIEW = "SET_SUBSCRIPTION_OVERVIEW";
export const SET_ALL_EXPANSES = "SET_ALL_EXPANSES";
export const SET_EXPENSE_TOTAL_COUNT = "SET_EXPENSE_TOTAL_COUNT";
export const SET_EXPENSE_OVERVIEW = "SET_EXPENSE_OVERVIEW";
export const SET_APPROVAL_EXPENSE = "SET_APPROVAL_EXPENSE";
export const SET_INVOICE_OVERVIEW_TABLE = "SET_INVOICE_OVERVIEW_TABLE";
export const SET_EXPENSE_OVERVIEW_TABLE = "SET_EXPENSE_OVERVIEW_TABLE";
export const SET_ALL_MESCELLANEOUS_EXPENSES = "SET_ALL_MESCELLANEOUS_EXPENSES";

//chat types
export const SET_ALL_CHATING_OF_USERS = "SET_ALL_CHATING_OF_USERS";
export const SET_ALL_CHAT_USERS = "SET_ALL_CHAT_USERS";

//Calender Types
export const SET_APPROVAL_PENDING_LEAVES = "SET_APPROVAL_PENDING_LEAVES";
export const SET_UPCOMIG_LEAVES = "SET_UPCOMIG_LEAVES";
export const SET_LEAVES_HISTORY = "SET_LEAVES_HISTORY";
export const SET_UPCOMING_MEETING_COUNT = "SET_UPCOMING_MEETING_COUNT";
export const SET_DISPLAY_CALENDER_DATA = "SET_DISPLAY_CALENDER_DATA";
export const SET_CALENDER_DATA_OF_DAY = "SET_CALENDER_DATA_OF_DAY";

// Support Types
export const SET_ALL_TICKETS = "SET_ALL_TICKETS";

// Notes Types
export const SET_ALL_NOTES = "SET_ALL_NOTES";

// All Project Discussion
export const SET_ALL_PROJECT_DISCUSSION = "SET_ALL_PROJECT_DISCUSSION";
export const SET_ALL_PROJECT_DISCUSSION_COMMENTS =
  "SET_ALL_PROJECT_DISCUSSION_COMMENTS";

// Scheduler Types
export const SET_SIGNLE_RESOURCE_SCHEDULE = "SET_SIGNLE_RESOURCE_SCHEDULE";
export const SET_ALL_RESOURCE_SCHEDULE = "SET_ALL_RESOURCE_SCHEDULE";
export const SET_SIGNLE_RESOURCE_SCHEDULE_CALENDER =
  "SET_SIGNLE_RESOURCE_SCHEDULE_CALENDER";

// Book their calender types
export const SET_BOOK_CALENDER_ADDED_TASK_DATA =
  "SET_BOOK_CALENDER_ADDED_TASK_DATA";
export const SET_ALL_BOOK_CALENDER_SCHEDULES =
  "SET_ALL_BOOK_CALENDER_SCHEDULES";
export const SET_ASSIGNED_MEMBERS_ARRAY = "SET_ASSIGNED_MEMBERS_ARRAY";
export const SET_ASSIGNED_MEMBERS_LEFT_ARRAY =
  "SET_ASSIGNED_MEMBERS_LEFT_ARRAY";

//Pipeline Types
export const SET_USER_PIPELINE = "SET_USER_PIPELINE";

// GANTT Types
export const SET_GANTT_DATA = "SET_GANTT_DATA";
export const SET_ALL_MODULES_OF_PROJECT = "SET_ALL_MODULES_OF_PROJECT";
export const SET_ALL_SPRINTS_OF_MODULES_OF_PROJECT =
  "SET_ALL_SPRINTS_OF_MODULES_OF_PROJECT";
export const SET_GANTT_MODULE_POPUP_DATA = "SET_GANTT_MODULE_POPUP_DATA";
export const SET_TASK_COLLABORATORS = "SET_TASK_COLLABORATORS";
export const SET_GANTT_TASK_EDIT_DATA = "SET_GANTT_TASK_EDIT_DATA";

//PROJECT PLANNING

export const SET_ALL_PROJECT_TASK = "SET_ALL_PROJECT_TASK";

//vault
export const SET_ALL_FOLDERS = "SET_ALL_FOLDERS";
export const SET_FILES_OF_FOLDER = "SET_FILES_OF_FOLDER";
export const SET_VAULT_OVERVIEW = "SET_VAULT_OVERVIEW";

//Dashboard types
export const SET_TODOS = "SET_TODOS";
export const SET_ALL_INVOICE_ISSUED_CHART_DATA =
  "SET_ALL_INVOICE_ISSUED_CHART_DATA";
export const SET_PAID_INVOICE_ISSUED_CHART_DATA =
  "SET_PAID_INVOICE_ISSUED_CHART_DATA";
export const SET_EXPENSE_CHART_DATA = "SET_EXPENSE_CHART_DATA";
export const SET_YEARLY_TOTAL_EXPENSE = "SET_YEARLY_TOTAL_EXPENSE";
export const SET_YEARLY_BILLED_EXPENSE = "SET_YEARLY_BILLED_EXPENSE";
export const SET_YEARLY_MIS_EXPENSE = "SET_YEARLY_MIS_EXPENSE";
export const SET_INVOICE_SUMMARY = "SET_INVOICE_SUMMARY";
export const SET_TODAYS_TASK = "SET_TODAYS_TASK";
export const SET_TASK_STATUS_BREAKDOWN = "SET_TASK_STATUS_BREAKDOWN";
export const SET_COST_VARIANCE = "SET_COST_VARIANCE";
export const SET_PROJECT_TIMELINE = "SET_PROJECT_TIMELINE";
export const SET_PROJECT_TASK_STATUS_REPORT = "SET_PROJECT_TASK_STATUS_REPORT";
export const SET_PROJECT_COUNTDOWN = "SET_PROJECT_COUNTDOWN";
export const SET_TICKET_SUMMARY_PERCENT = "SET_TICKET_SUMMARY_PERCENT";
export const SET_PROJECT_COMPLETION_STATUS = "SET_PROJECT_COMPLETION_STATUS";

// Timesheet types
export const SET_MONTH_VIEW_TIMESHEET_DATA = "SET_MONTH_VIEW_TIMESHEET_DATA";
export const SET_DAY_VIEW_TIMESHEET_DATA = "SET_DAY_VIEW_TIMESHEET_DATA";
export const SET_SELETCED_FILTERNAME_MEMBER_ID =
  "SET_SELETCED_FILTERNAME_MEMBER_ID";
export const SET_CSV_EXPORT_TIMESHEET_DATA = "SET_CSV_EXPORT_TIMESHEET_DATA";

/*==========================================
          Super Admin Types
  ===========================================*/
export const SET_SUPERADMIN_ORGANIZATIONS = "SET_SUPERADMIN_ORGANIZATIONS";
export const SET_PERTICULAR_WORKSPACE_INFO = "SET_PERTICULAR_WORKSPACE_INFO";
export const SET_ORGANIZATION_OVERVIEW = "SET_ORGANIZATION_OVERVIEW";
export const GET_SINGLE_ORGANIZATION_OVERVIEW =
  "GET_SINGLE_ORGANIZATION_OVERVIEW";
export const GET_SUPERADMIN_FILTERNAME = "GET_SUPERADMIN_FILTERNAME";
export const SET_MANUAL_RETRY_COUNT = "SET_MANUAL_RETRY_COUNT";

/*==========================================
              Walkthrough
============================================*/

export const SET_WALKTHROUGH_PAGE = "SET_WALKTHROUGH_PAGE";

/*========================================================
              workflows local actions
==========================================================*/

export const SET_ADD_CONTENT_BLOCK = "SET_ADD_CONTENT_BLOCK";
export const SET_ADD_CONTENT_TEXT_INPUT_FIELD =
  "SET_ADD_CONTENT_TEXT_INPUT_FIELD";
export const SET_ADD_CONTENT_SINGLE_QUESTION =
  "SET_ADD_CONTENT_SINGLE_QUESTION";
export const SET_ADD_CONTENT_MULTIPLE_QUESTION =
  "SET_ADD_CONTENT_MULTIPLE_QUESTION";
export const SET_ADD_CONTENT_SUBTASKS = "SET_ADD_CONTENT_SUBTASKS";
export const SET_ADD_CONTENT_NUMBER_INPUT_FIELD =
  "SET_ADD_CONTENT_NUMBER_INPUT_FIELD";
export const SET_ADD_CONTENT_DATE_INPUT_FIELD =
  "SET_ADD_CONTENT_DATE_INPUT_FIELD";
export const SET_ADD_CONTENT_ATTACHMENTS = "SET_ADD_CONTENT_ATTACHMENTS";
export const SET_ADD_CONTENT_CONDITIONS = "SET_ADD_CONTENT_CONDITIONS";
export const SET_ALL_STEPS_DATA = "SET_ALL_STEPS_DATA";

// workboard types

export const SET_ALL_PROJECTS_WORKBOARD = "SET_ALL_PROJECTS_WORKBOARD";

/*==========================================
              Payment Types
============================================*/
export const SET_FUTURE_PAYMENT_INVOICE = "SET_FUTURE_PAYMENT_INVOICE";
export const SET_PAYMENT_HISTORY = "SET_PAYMENT_HISTORY";
export const SET_PAYMENT_SAVED_CARDS = "SET_PAYMENT_SAVED_CARDS";
export const SET_CUSTOMER_ACCOUTN_BALENCE = "SET_CUSTOMER_ACCOUTN_BALENCE";

/*==========================================
             COMMAND CENTER
============================================*/

export const SET_ALL_USERS_ROLES = "SET_ALL_USERS_ROLES";
export const SET_ALL_CUSTOM_FIELDS = "SET_ALL_CUSTOM_FIELDS";
export const SET_CLIENT_ALL_CUSTOME_FIELDS = "SET_CLIENT_ALL_CUSTOME_FIELDS";
export const SET_MEMBER_ALL_CUSTOME_FIELDS = "SET_MEMBER_ALL_CUSTOME_FIELDS";
export const SET_PROJECT_ALL_CUSTOME_FIELDS = "SET_PROJECT_ALL_CUSTOME_FIELDS";
export const GET_FIELDS_VALUE_BY_ENTITY = "GET_FIELDS_VALUE_BY_ENTITY";
export const SET_DEAL_ALL_CUSTOME_FIELDS = "SET_DEAL_ALL_CUSTOME_FIELDS";

/*==========================================
           PROJECT DOCS
============================================*/

export const SET_PROJECT_ALL_DOCS = "SET_PROJECT_ALL_DOCS";

/*==========================================
         WORKFLOWS TYPES
============================================*/

export const SET_ALL_WORKFLOWS = "SET_ALL_WORKFLOWS";
export const SET_SINGLE_WORKFLOW_DATA = "SET_SINGLE_WORKFLOW_DATA";
export const SET_WORKFLOW_ALL_STEPS = "SET_WORKFLOW_ALL_STEPS";
export const SET_WORKFLOW_ALL_TASKS = "SET_WORKFLOW_ALL_TASKS";
export const SET_WORKFLOW_ALL_SUBTASKS = "SET_WORKFLOW_ALL_SUBTASKS";
export const SET_ALL_INSTANCE_OF_USER = "SET_ALL_INSTANCE_OF_USER";
export const SET_SINGLE_INSTANCE_DATA = "SET_SINGLE_INSTANCE_DATA";
