FROM nginx

COPY ssl/cert_chain.crt ./etc/ssl/cert_chain.crt
COPY ssl/server.key ./etc/ssl/server.key
COPY nginx.conf ./etc/nginx/nginx.conf

EXPOSE 443

# Start Nginx when the container has provisioned.
CMD ["nginx", "-g", "daemon off;"]
