module.exports = {
    SUCCESS: {code:"SUCCESS",message:"Success"},
    INTERNAL_SERVER_ERROR: {code:"INTERNAL_SERVER_ERROR",message:"Internal Server Error"},
    INVALID_INPUT : {code:"INVALID_INPUT",message:"Invalid input"}, 
    LOGIN_FAILED: {code:"LOGIN_FAILED",message:"Login Failed"},
    INVALID_ENVIRONMENT_USER: {code:"INVALID_ENVIRONMENT_USER",message:"Invalid Environment User"},
    EXCEED_EMAIL_LIMIT: {code: "EXCEED_EMAIL_LIMIT", message: "Maximum number of registration with same email address"},
    INVALID_MEDIA_TYPE: {code: "INVALID_MEDIA_TYPE", message: "Invalid Media Type"},
    INVALID_CONDITION: {code: "INVALID_CONDITION", message: "Invalid Condition"},
    USERNAME_EMAIL_REQUIRED: {code: "USERNAME_EMAIL_REQUIRED", message: "Username Email Required"},
    INVALID_MEDIA: {code: "INVALID_MEDIA", message: "Invalid Media"},
    INVALID_DATA: {code: "INVALID_DATA", message: "Invalid data"},
    NOT_FOUND: {code: "NOT_FOUND", message: "Resource not found"},
    INVALID_FILE: {code: "INVALID_FILE", message: "Invalid File"},  
    LIMIT_REACHED : {code: "LIMIT_REACHED", message: "Order limit reached"},
    LIMIT_EXCEEDED : {code: "LIMIT_EXCEEDED", message: "Limit exceeded"},
    ERROR_EMAIL : {code: "ERROR_EMAIL", message: "Email sending failed"},
    VALIDATION_FAILED: {code: "VALIDATION_FAILED", message: "Validation rule failed"},
    INVALID_TOKEN: {code: "INVALID_TOKEN", message: "Access Token is invalid"},
    USER_NOT_EXIST: {code: "USER_NOT_EXIST", message: "User does not exist"},
    USER_ALREADY_EXIST: {code: "USER_ALREADY_EXIST", message: "User already exist"},
    MISSING_QUERY_PARAM: {code: "MISSING_QUERY_PARAM", message: "Query param is not provided"},
    OPERATION_NOT_SUPPORTED: {code: "INTERNAL ORG UPDATION", message:"Cannot modify internal oraganization"},
    MISSING_ID: {code: "MISSING_ID", message: "Id is not provided"},
    ACCESS_DENIED: {code: "ACCESS_DENIED", message: "Access Denied"},
    TASK_ALREADY_EXIST: {code:"TASK_ALREADY_EXIST", message: "Task already exist"},
    TASK_NOT_EXIST: {code:"TASK_NOT_EXIST", message:"Task not exist"},
    USER_NOT_ACTIVE: {code:"USER_NOT_ACTIVE", message:"User not active"},
    ORGANISATION_INACTIVE: {code:"ORGANISATION_INACTIVE", message:"Organisation is inactive"},
    ORGANIZATION_ALREADY_EXIST: {code:"ORGANIZATION_ALREADY_EXIST", message:"Organisation already exist"},
    ORGANIZATION_DOES_NOT_EXIST: {code:"ORGANIZATION_DOES_NOT_EXIST", message:"Organisation does not exist"},
    CUSTOMER_NOT_EXIST: {code: "CUSTOMER_NOT_EXIST", message: "Customer not exist"},
    CUSTOMER_ALREADY_EXIST: {code: "CUSTOMER_ALREADY_EXIST", message: "Customer already exist"},
    CANNOT_APPROVE_LEAVE: {code: "CANNOT_APPROVE_LEAVE", message: "Cannot approve leave"},
    NOTIFICATION_NOT_EXIST: {code: "NOTIFICATION_NOT_EXIST", message: "Notification not exist"},
    INVALID_PLAN: {code: "INVALID_PLAN", message: "Plan not exist"} ,
    TARGET_ALREADY_EXIST: { code : "TARGET_ALREADY_EXIST", message:"Target for the given user or organisation already exists" },
    ORGANISATION_TARGET_NOT_EXIST: { code : "ORGANISATION_TARGET_NOT_EXIST", message:"Organisation Target must be set before creating employee target." },
    PROJECT_NOT_EXIST:{ code:'PROJECT_NOT_EXIST', message : "Project do not exists" },
    SCHEDULE_DOES_NOT_EXIST:{code: 'SCHEDULE_DOES_NOT_EXIST', message: "Schedule does not exist"},
    SCHEDULE_ALREADY_EXISTS:{code: 'SCHEDULE_ALREADY_EXISTS', message: "Schedule already exists"},
    TICKET_DOES_NOT_EXIST: {code: 'TICKET_DOES_NOT_EXIST', message : "Ticket does not exist"},
    TICKET_ALREADY_EXISTS: {code: 'TICKET_ALREADY_EXISTS', message: "Ticket already exists"},
    NOTE_DOES_NOT_EXIST: {code: 'NOTE_DOES_NOT_EXIST', message: "Note does not exist"},
    NOTE_ALREADY_EXISTS: {code: 'NOTE_ALREADY_EXISTS', message: "Note already exists"}, 
    DISCUSSION_DOES_NOT_EXIST:{code: 'DISCUSSION_DOES_NOT_EXIST', message : "Discussion does not exist"},
    DISCUSSION_ALREADY_EXISTS:{code: 'DISCUSSION_ALREADY_EXISTS', message: "Discussion already exists"}, 
    TODO_DOES_NOT_EXIST:{code:'TODO_DOES_NOT_EXIST', message: "Todo does not exist"},
    TODO_ALREADY_EXISTS: {code: "TODO_ALREADY_EXISTS", message: "Todo already exists"}, 
    SCRUM_DOES_NOT_EXIST: {code:'SCRUM_DOES_NOT_EXIST', message : "Scrum does not exist"},
    SCRUM_ALREADY_EXISTS: {code:'SCRUM_ALDREADY_EXISTS', message: "Scrum already exists"},    
    TASK_ALREADY_EXISTS:{code: 'TASK_ALREADY_EXISTS', message : "Task alreadt exists"},
    TASK_DOES_NOT_EXIST:{code: 'TASK_DOES_NOT_EXIST', message: "Task does not exist"},   
    PROJECT_ALREADY_EXIST: {code: 'PROJECT_ALREADY_EXIST', message: "Project already exists"},    
    EXPENSESUBSCRIPTION_DOES_NOT_EXIST: {code: 'EXPENSESUBSCRIPTION_DOES_NOT_EXIST', message:"this expense subscription does not exist"},
    EXPENSESUBSCRIPTION_ALREADY_EXISTS: {code: 'EXPENSESUBSCRIPTION_ALREADY_EXISTS', message:"this expense subscription already exists"},   
    EXPENSE_DOES_NOT_EXIST: {code: 'EXPENSE_DOES_NOT_EXIST', message:"expense does not exist"},
    EXPENSE_ALREADY_EXISTS: {code: 'EXPENSE_ALREADY_EXISTS', message: "expense already exists"},
    INVOICE_ALREADY_EXISTS: {code: 'INVOICE_ALREADY_EXISTS', message: "Invoice already exists"},
    FILE_ALREADY_EXISTS:{code: 'FILE_ALREADY_EXISTS', message: "file already exists"},
    FILE_DOES_NOT_EXIST:{code: 'FILE_DOES_EXIST', message:"file does not exist"},
    FAQ_ALREADY_EXISTS:{code: 'FAQ_ALREADY_EXISTS', message:"Faq already exists"},
    FAQ_DOES_NOT_eXIST:{code:'FAQ_DOES_NOT_EXIST', message:"Faq does not exist"},
    SUPPORT_ALREADY_EXISTS:{ code : "SUPPORT_ALREADY_EXISTS", message:"Support question already exists" },
    SUPPORT_DOES_NOT_EXISTS:{ code : "SUPPORT_DOES_NOT_EXISTS", message:"Support question does not exists" },
    PROPOSAL_ALREADY_EXISTS:{code: "PROPOSAL_ALREADY_EXISTS", message:"proposal already exists"},
    PROPOSAL_DOES_NOT_EXIST:{code:"PROPOSAL_DOES_NOT_EXIST", message:"proposal does not exist"},
    FOLDER_ALREADY_EXISTS:{ code : "FOLDER_ALREADY_EXISTS", message:"Duplicate folder name" },
    MISSING_REQUEST_BODY:{code:"MISSING_REQUEST_BODY", message : "Missing Request Body object" },
    WORKBOARD_ALREADY_EXISTS:{code:"WORKBOARD_ALREADY_EXISTS", message:"Workboard already exists"},
    WORKBOARD_DOES_NOT_EXIST:{code:"WORKBOARD_DOES_NOT_EXIST", message:"Workboard does not exist"},
    STAGE_ALREADY_EXISTS_FOR_PROJECT:{ code : "STAGE_ALREADY_EXISTS_FOR_PROJECT", message:"A stage with this name already exists for this project" },
    STAGE_DOES_NOT_EXIST:{ code : "STAGE_DOES_NOT_EXIST", message:"Stage does not exists" }, 
    STAGE_CANT_BE_ZERO:{code:"STAGE_CANT_BE_ZERO", message:"Atleast one stage is required in the system"},
    STAGE_HAS_TASKS_CANT_DELETE:{code:"STAGE_HAS_TASKS_CANT_DELETE", message:"This stage has some tasks, please delete all tasks in this stage and then retry"},
    STAGE_COMPLETED_CANT_DELETE:{code:"STAGE_COMPLETED_CANT_DELETE", message:"This stage cannot be deleted as it's required to calculate some metrics for your reports"},
    STAGE_COMPLETED_CANT_EDIT:{code:"STAGE_COMPLETED_CANT_EDIT", message:"This stage name cannot be edited as it's required to calculate some metrics for your reports"},
    PIPELINE_ALREADY_EXISTS_FOR_USER_AND_TASK:{ code : "PIPELINE_ALREADY_EXISTS_FOR_USER_AND_TASK", message:"Pipeline already exists for this particular and user values" },
    PIPELINE_DOES_NOT_EXIST:{ code : "PIPELINE_DOES_NOT_EXIST", message:"Pipeline does not exists" },
    WORKFLOW_ALREADY_EXISTS:{code: "WORKFLOW_ALREADY_EXISTS", message:"workflow already exists"},
    WORKFLOW_DOES_NOT_EXIST:{code:"WORKFLOW_DOES_NOT_EXIST", message:"workflow does not exist"},
    WSTEP_ALREADY_EXISTS:{code: "WSTEP_ALREADY_EXISTS", message:"wstep already exists"},
    WSTEP_ALREADY_EXISTS_FOR_WORKFLOW:{code: "WSTEP_ALREADY_EXISTS_FOR_WORKFLOW", message:"This step name already exists for this workflow, please try a different step name"},
    WSTEP_DOES_NOT_EXIST:{code:"WSTEP_DOES_NOT_EXIST", message:"wstep does not exist"},
    WTASK_ALREADY_EXISTS:{code: "WTASK_ALREADY_EXISTS", message:"wtask already exists"},
    WTASK_ALREADY_EXISTS_FOR_WSTEP:{code: "WTASK_ALREADY_EXISTS_FOR_WSTEP", message:"This task name already exists for this step, please try a different name"},
    WTASK_DOES_NOT_EXIST:{code:"WTASK_DOES_NOT_EXIST", message:"wtask does not exist"},
    WSUBTASK_ALREADY_EXISTS:{code: "WSUBTASK_ALREADY_EXISTS", message:"wsubtask already exists"},
    WSUBTASK_ALREADY_EXISTS_FOR_WTASK:{code: "WSUBTASK_ALREADY_EXISTS_FOR_WTASK", message:"This subtask name already exists for this task, please try a different name"},
    WSUBTASK_DOES_NOT_EXIST:{code:"WSUBTASK_DOES_NOT_EXIST", message:"wsubtask does not exist"}, 
    WINSTANCE_ALREADY_EXISTS:{code: "WINSTANCE_ALREADY_EXISTS", message:"winstance already exists"},
    WINSTANCE_DOES_NOT_EXIST:{code:"WINSTANCE_DOES_NOT_EXIST", message:"winstance does not exist"}, 
    FIELD_DOES_NOT_EXIST:{code:"FIELD_DOES_NOT_EXIST", message:"Field does not exist"},
    FIELD_ALREADY_EXISTS:{code:"FIELD_ALREADY_EXISTS", message:"Field already exists"},
    FVALUE_DOES_NOT_EXIST:{code:"FVALUE_DOES_NOT_EXISTS", message:"Fvalue does not exist"},
    FVALUE_ALREADY_EXISTS:{code:"FVALUE_ALREADY_EXISTS", message:"Fvalue already exists"},
    DOC_DOES_NOT_EXIST:{code:"DOC_DOES_NOT_EXISTS", message:"Doc does not exist"},
    DOC_ALREADY_EXISTS_FOR_PROJECT:{code:"DOC_ALREADY_EXISTS_FOR_PROJECT", message:"Doc with this name already exists for this project"},
    INVALID_EMAIL_OR_PASSWORD:{code:"INVALID_EMAIL_OR_PASSWORD", message:"The password or email is invalid"},
    PASSWORD_DOES_NOT_MATCH:{code:"PASSWORD_DOES_NOT_MATCH", message:"The passwords don't match"},
    USER_WITH_EMAIL_DOES_NOT_EXIST:{code:"USER_WITH_EMAIL_DOES_NOT_EXIST", message:"User with this email does not exist"},
    PLAN_DOES_NOT_EXIST:{code:"PLAN_DOES_NOT_EXIST", message:"This plan does not exist, please check spelling"},
    FEATURE_DOES_NOT_EXIST:{code:"FEATURE_DOES_NOT_EXIST", message:"This feature does not exist, please check spelling"}
}
