export const SET_AUTH_LOADER = "SET_AUTH_LOADER";
export const SET_ACTIVE_ACCOUNTS = "SET_ACTIVE_ACCOUNTS";
export const SET_NOTACTIVE_ACCOUNTS = "SET_NOTACTIVE_ACCOUNTS";

export const CONTACTS_LOADERS = "CONTACT_LOADERS";
export const GET_ALL_CONTACTS = "GET_ALL_CONTACTS";

export const EVENT_LOADERS = "EVENT_LOADERS";
export const GET_ALL_EVENTS = "GET_ALL_EVENTS";

export const GET_EMAIL_THREADS = "GET_EMAIL_THREADS";
export const SET_EMAIL_LOADER = "SET_EMAIL_LOADER";

export const SET_DRAFTS_LOADER = "SET_DRAFTS_LOADER";
export const GET_ALL_DRAFTS = "GET_ALL_DRAFTS";